### ISSUE TITLE
Having trouble using docker

### ISSUE THREAD

**Issue by treemandan** [r4victor/syncabook#6]
while using this line in cmd
docker run -v "%cd%":/ebooks/after syncabook sync /ebooks/after

docker gives me this
C:\syncabook>docker run -v "%cd%":/ebooks/after syncabook sync /ebooks/after
Calling afaligner for syncing...
Traceback (most recent call last):
  File "/usr/local/bin/syncabook", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/syncabook/__main__.py", line 147, in main
    sync(
  File "/usr/local/lib/python3.8/site-packages/syncabook/sync.py", line 15, in sync
    sync_map = align(
  File "/usr/local/lib/python3.8/site-packages/afaligner/__init__.py", line 84, in align
    text_paths = (os.path.join(text_dir, f) for f in sorted(os.listdir(text_dir)))
FileNotFoundError: [Errno 2] No such file or directory: '/ebooks/after/sync_text'

not sure what I'm doing wrong

syncabook dir is c:/syncabook

**Comment by r4victor** [comment]
Hi, @treemandan. Where do you keep the text files for syncing? As described in the [README](https://github.com/r4victor/syncabook#ebook-production), **syncabook** expects your texts to be in the XHTML format in the `sync_text` directory (see examples [here](https://github.com/r4victor/synclibrivox/tree/master/books)). Ensure that the `c:/syncabook/sync_text/` directory exists and contains the XHTML files.

It seems you're using Windows. Please note that the **afaligner** library that performs syncing [doesn't work properly](https://github.com/r4victor/afaligner/issues/2) on Windows at the moment because of the memory overcommit (the Docker won't help). Syncing small files may work. Consider getting a Linux / Mac OS machine if you want to sync files of any reasonable size.

**Comment by treemandan** [comment]
thanks for the quick reply.

I have the xhtml file (made with syncabook earlier) in c:/syncabook/ebooks/after/sync_text/

thanks for the info, I had a memory error when I ran sync on python 3.7 32bit (couldn't get afaligner installed on 64bit python). I thought that if I ran it through docker it might fix that issue, sounds like it won't
